# Generated by Django 5.1.1 on 2024-10-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_staffuserprofile_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuserprofile',
            name='brand_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
