# Generated by Django 5.1.1 on 2024-10-11 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_store_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='store',
            name='created_at',
        ),
    ]
