# Generated by Django 5.1.1 on 2024-10-11 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_email_alter_user_phone_number'),
        ('core', '0003_remove_store_admin_remove_store_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.adminuserprofile'),
            preserve_default=False,
        ),
    ]
