# Generated by Django 5.1.1 on 2024-11-09 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_productsale_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.sale'),
        ),
    ]
