# Generated by Django 5.1.1 on 2024-11-09 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_productsale_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.sale'),
            preserve_default=False,
        ),
    ]
