# Generated by Django 5.1.1 on 2024-11-09 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
        ('core', '0006_alter_sale_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='account.staffuserprofile'),
        ),
    ]
