# Generated by Django 5.1.1 on 2024-10-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_sale_products_productsale_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='daily_target',
            field=models.FloatField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'store')},
        ),
    ]
