# Generated by Django 5.1.1 on 2024-11-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sale_sale_made_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='previous_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
