# Generated by Django 5.1.1 on 2024-10-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_price_product_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
