# Generated by Django 5.1.1 on 2024-10-27 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_adminuserprofile_brand_name'),
        ('core', '0015_sale_amount_paid_sale_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='account.adminuserprofile'),
        ),
    ]
